spring.application.name=bonos-api-backend

# Perfil activo
spring.profiles.active=local

# JPA común
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Inicialización
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true